# Generated by Django 5.2.6 on 2025-09-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gymsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymSession',
        ),
    ]
