# Generated by Django 5.2.6 on 2025-09-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendancerecord_notification_userservicepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sessions_included',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited'),
        ),
    ]
