# Generated by Django 5.2.6 on 2025-09-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_sessions_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sessions_included',
            field=models.PositiveIntegerField(default=0, help_text='Number of sessions included in the package'),
        ),
    ]
