# Generated by Django 5.2.6 on 2025-09-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usercheckin_attendanceqrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercheckin',
            name='service_package',
        ),
        migrations.RemoveField(
            model_name='usercheckin',
            name='user',
        ),
        migrations.DeleteModel(
            name='AttendanceQRCode',
        ),
        migrations.DeleteModel(
            name='UserCheckIn',
        ),
    ]
