# Generated by Django 5.2.6 on 2025-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_usercheckin_service_package_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userservicepackage',
            old_name='sessions_remaining',
            new_name='sessions_used',
        ),
        migrations.AddField(
            model_name='userservicepackage',
            name='total_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
