# Generated by Django 5.2.6 on 2025-09-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_sessions_remaining_userservicepackage_sessions_used_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.RenameField(
            model_name='userservicepackage',
            old_name='sessions_used',
            new_name='tickets_used',
        ),
        migrations.RenameField(
            model_name='userservicepackage',
            old_name='total_sessions',
            new_name='total_tickets',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='sessions_included',
        ),
        migrations.AddField(
            model_name='appointment',
            name='tickets_included',
            field=models.PositiveIntegerField(default=0, help_text='Number of tickets included in the package'),
        ),
    ]
