# Generated by Django 5.2.6 on 2025-09-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_timeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('session_reminder', 'Session Reminder'), ('package_expiry', 'Package Expiry'), ('low_tickets', 'Low Tickets'), ('attendance', 'Attendance Confirmation'), ('appointment_reminder', 'Appointment Reminder')], max_length=20),
        ),
    ]
