# Generated by Django 5.2.6 on 2025-09-12 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_remove_servicepackage_sessions_included_and_more'),
        ('core', '0011_notification_is_urgent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userservicepackage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'service_package'), name='unique_active_package_per_user_service'),
        ),
    ]
