# Generated by Django 5.2.6 on 2025-09-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userservicepackage_unique_active_package_per_user_service'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userservicepackage',
            name='unique_active_package_per_user_service',
        ),
    ]
