# Generated by Django 5.2.6 on 2025-09-08 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('gym', 'Gym'), ('sauna', 'Sauna'), ('massage', 'Massage')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sessions_included', models.PositiveIntegerField(help_text='Number of sessions included (0 for unlimited)')),
                ('validity_days', models.PositiveIntegerField(help_text='Package validity in days')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False, help_text='Auto-renew package when expired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['service_type', 'price'],
            },
        ),
    ]
