# Generated by Django 5.2.6 on 2025-09-10 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_staff_staffattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepackage',
            name='sessions_included',
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='tickets_included',
            field=models.PositiveIntegerField(default=0, help_text='Number of tickets included (0 for unlimited)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in RWF', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
