# Generated by Django 5.2.6 on 2025-09-06 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with this phone number already exists.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+250xxxxxxxxx' where x is a digit (12 digits total)", regex='^\\+250\\d{9}$')]),
        ),
    ]
