# Generated by Django 5.2.6 on 2025-09-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('staff', 'Staff')], default='client', max_length=10),
        ),
    ]
